# Generated by Django 4.1.2 on 2022-12-13 10:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
                ('espacio', models.CharField(max_length=100)),
                ('aforo_max', models.IntegerField(blank=True, default=None, null=True)),
                ('n_asistentes', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(default=None, max_length=500)),
                ('fecha', models.DateTimeField()),
                ('lugar', models.CharField(max_length=100)),
                ('aforo_max', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('n_asistentes', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('premio', models.CharField(blank=True, max_length=255, null=True)),
                ('coste', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Ponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=255)),
                ('apellidos', models.CharField(default=None, max_length=255)),
                ('especialidades', models.CharField(default=None, max_length=255)),
                ('empresa', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('correo', models.EmailField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Utilice el siguiente formato: '+999999999'. Se permite introducir hasta 15 cifras.", regex='^\\+?1?\\d{9,15}$')])),
                ('otras_formas_de_contacto', models.TextField(blank=True, default=None, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ponente_Conferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.conferencia')),
                ('ponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ponente')),
            ],
        ),
    ]
