# Generated by Django 4.1.2 on 2022-12-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ponente_conferencia',
            unique_together={('ponente', 'conferencia')},
        ),
    ]
