---
- name: One way to avoid apt_key once it is removed from your distro
  block:
    - name: Postgresql |no apt key
      ansible.builtin.get_url:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        dest: /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg

    - name: Postgresql | apt source
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/apt.postgresql.org.gpg] http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main"
        state: present

- name: Install packages
  become: true
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - git
    - postgresql-14
    - python3.8
    - python3-pip
    - python3-psycopg2
    - python3-virtualenv
    - virtualenv
    - nginx
    - libpq-dev
    - python-setuptools
    - build-essential
    - python-dev
    - make
    - m4
