# Generated by Django 4.1.2 on 2022-10-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("fecha", models.DateTimeField()),
                ("lugar", models.CharField(max_length=100)),
                ("aforo_max", models.IntegerField(default=None)),
                (
                    "n_asistentes",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("premio", models.CharField(max_length=255)),
                ("coste", models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
