# Generated by Django 4.1.2 on 2022-10-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_evento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conferencia",
            name="aforo_max",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="evento",
            name="aforo_max",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="evento",
            name="premio",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
