# Generated by Django 4.1.2 on 2022-10-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_conferencia_aforo_max_alter_evento_aforo_max_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ponente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("lugar", models.CharField(max_length=100)),
                ("aforo_max", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "n_asistentes",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("premio", models.CharField(blank=True, max_length=255, null=True)),
                ("coste", models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="evento",
            name="descripcion",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
