# Generated by Django 4.1.2 on 2022-10-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_ponente_evento_descripcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="descripcion",
            field=models.TextField(default=None, max_length=500),
        ),
    ]
