# Generated by Django 4.1.2 on 2022-10-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_evento_descripcion"),
    ]

    operations = [
        migrations.RemoveField(model_name="ponente", name="aforo_max",),
        migrations.RemoveField(model_name="ponente", name="coste",),
        migrations.RemoveField(model_name="ponente", name="lugar",),
        migrations.RemoveField(model_name="ponente", name="n_asistentes",),
        migrations.RemoveField(model_name="ponente", name="premio",),
        migrations.AddField(
            model_name="ponente",
            name="apellidos",
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name="ponente",
            name="conferencias_impartidas",
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name="ponente",
            name="correo",
            field=models.EmailField(
                blank=True, default=None, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="ponente",
            name="empresa",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ponente",
            name="especialidades",
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name="ponente",
            name="otras_formas_de_contacto",
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="ponente",
            name="telefono",
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="ponente",
            name="nombre",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
