# Generated by Django 4.1.2 on 2022-11-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_ponente_aforo_max_remove_ponente_coste_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="aforo_max",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="evento",
            name="n_asistentes",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
