# Generated by Django 4.1.2 on 2022-11-22 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_evento_coste"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ponente",
            name="telefono",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=12,
                null=True,
                validators=[django.core.validators.MinLengthValidator(4)],
            ),
        ),
    ]
