# Generated by Django 4.1.2 on 2022-11-22 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_ponente_telefono"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ponente",
            name="telefono",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=9,
                null=True,
                validators=[django.core.validators.MinLengthValidator(9)],
            ),
        ),
    ]
