# Generated by Django 4.1.2 on 2022-11-23 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_ponente_telefono"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ponente",
            name="telefono",
            field=models.CharField(
                blank=True,
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Debe introducir el número de teléfono con el siguiente formato: '+999999999'. Se permite introducir hasta 15 cifras.",
                        regex="^+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
    ]
