# Generated by Django 4.1.2 on 2022-11-24 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_ponente_telefono"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ponente",
            name="correo",
            field=models.EmailField(
                blank=True, default=None, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="ponente",
            name="telefono",
            field=models.CharField(
                blank=True,
                max_length=17,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Utilice el siguiente formato: '+999999999'. Se permite introducir hasta 15 cifras.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
    ]
