# Generated by Django 4.1.2 on 2022-11-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_ponente_correo_alter_ponente_telefono"),
    ]

    operations = [
        migrations.RemoveField(model_name="ponente", name="conferencias_impartidas",),
        migrations.RemoveField(model_name="conferencia", name="ponente",),
        migrations.AddField(
            model_name="conferencia",
            name="ponente",
            field=models.ManyToManyField(to="api.ponente"),
        ),
    ]
