# Generated by Django 4.1.2 on 2022-10-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conferencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ponente", models.CharField(max_length=100)),
                ("tema", models.CharField(max_length=255)),
                ("fecha", models.DateTimeField()),
                ("espacio", models.CharField(max_length=100)),
            ],
        ),
    ]
