# Generated by Django 4.1.2 on 2022-10-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferencia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conferencia",
            name="aforo_max",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="conferencia",
            name="n_asistentes",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
