# Generated by Django 4.1.2 on 2022-10-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferencia", "0002_conferencia_aforo_max_conferencia_n_asistentes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conferencia",
            name="aforo_max",
            field=models.IntegerField(default=None),
        ),
    ]
