name: Docker Image CI

on:
  workflow_run:
    workflows: [Django CI]
    types: [completed]
    branches:
      - main

jobs:

  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - 
      name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag rafsanesp/innograma:latest
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Push the Docker image
      run: docker push rafsanesp/innograma
